weights: /content/drive/MyDrive/colabnotebooks/road_damage_detection/Road_Damage_Detection_YOLOv5/trained_weights/RDD_yolov55/weights/last.pt
cfg: models/yolov5s.yaml
data: rdd.yaml
hyp: data/hyp.scratch.yaml
epochs: 100
batch_size: 8
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: /content/drive/MyDrive/colabnotebooks/road_damage_detection/Road_Damage_Detection_YOLOv5/trained_weights
entity: null
name: RDD_yolov5
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: /content/drive/MyDrive/colabnotebooks/road_damage_detection/Road_Damage_Detection_YOLOv5/trained_weights/RDD_yolov56
total_batch_size: 8
